import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getHeaderAndHomePageData } from "@/lib/wordpress";
import Header from "@/components/header/Header";
import FooterSection from "@/components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { themeSettings, navMenus } = await getHeaderAndHomePageData();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header themeSettings={themeSettings} navMenus={navMenus} />
        <div className="flex-grow flex flex-col">
          {children}
        </div>
        <FooterSection themeSettings={themeSettings} navMenus={navMenus} />
      </body>
    </html>
  );
}
